(("default" . ((user-emacs-directory . "~/.emacs.d")))
 ("doom" . ((user-emacs-directory . "~/Git/doom")
           (env . (("DOOMDIR" . "~/.doom.d")))))
 ("spacemacs" . ((user-emacs-directory . "~/Git/spacemacs")
                 (env . (("SPACEMACSDIR" . "~/.spacemacs.d"))))))
